### PR TITLE
testing: use t.Cleanup() for test utilities, remove gotest.tools dependency

### PR DESCRIPTION
**Pull request by thaJeztah**
- [x] depends on https://github.com/moby/term/pull/33

LOL; cleaning up branches, found this one that I apparently forgot about

### CODE REVIEW

**Comment by thaJeztah** [comment]
oh, hm, interesting; I just realised this was added in Go 1.14


https://github.com/golang/go/blob/go1.14/src/testing/testing.go#L547


so why does this work on go 1.12 and 1.13? 🤔 

https://github.com/golang/go/blob/go1.12/src/testing/testing.go#L498
https://github.com/golang/go/blob/go1.13/src/testing/testing.go#L542

**Comment by thaJeztah** [comment]
rebased, now that https://github.com/moby/term/pull/19 was merged; this should now likely fail on Go1.13, but pass on Go1.14 and 1.15

**Comment by thaJeztah** [comment]
Hmmm.... doesn't fail. I'm confused

**Comment by thaJeztah** [comment]
What the???? It's showing that it's installing Go 1.13, but it's actually running Go 1.14.10?

```
panic: CLEANED UP [recovered]
	panic: CLEANED UP

goroutine 33 [running]:
testing.tRunner.func1.1(0x5f04c0, 0x684780)
	/opt/hostedtoolcache/go/1.14.10/x64/src/testing/testing.go:999 +0x319
testing.tRunner.func1(0xc000117320)
```

**Comment by thaJeztah** [comment]
Oh!! I know what's wrong; look at `GOROOT`:

```
Run actions/checkout@v2
  with:
    repository: moby/term
    token: ***
    ssh-strict: true
    persist-credentials: true
    clean: true
    fetch-depth: 1
    lfs: false
    submodules: false
  env:
    GOROOT: /opt/hostedtoolcache/go/1.13.15/x64
```

And this is how we run our tests:

```yaml
run: sudo go test -v ./...
```

We're using `sudo`, not `sudo -E`, so it will likely use the default `GOROOT`

**Comment by thaJeztah** [comment]
Getting closer;

```
# internal/cpu
compile: version "go1.13.15" does not match go tool version "go1.14.10"
# runtime/internal/atomic
compile: version "go1.13.15" does not match go tool version "go1.14.10"
```

**Comment by thaJeztah** [comment]
Looks like `PATH` doesn't match the right version of Golang;

```
sudo -E sh -c 'go version && go env && go test -v ./...'
  shell: /bin/bash -e {0}
  env:
    GOROOT: /opt/hostedtoolcache/go/1.13.15/x64
go version go1.14.10 linux/amd64
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/runner/.cache/go-build"
GOENV="/home/runner/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/runner/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/hostedtoolcache/go/1.13.15/x64"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/hostedtoolcache/go/1.13.15/x64/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/runner/work/term/term/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build834888489=/tmp/go-build -gno-record-gcc-switches"
go: downloading golang.org/x/sys v0.0.0-20200831180312-196b9ba8737a
go: downloading gotest.tools/v3 v3.0.2
go: downloading github.com/creack/pty v1.1.11
go: downloading github.com/google/go-cmp v0.4.0
go: downloading github.com/pkg/errors v0.9.1
# internal/cpu
compile: version "go1.13.15" does not match go tool version "go1.14.10"
```

**Comment by thaJeztah** [comment]
Looks to be the `PATH` indeed; It's because `sudo` (as a security measure) does not inherit `PATH` https://unix.stackexchange.com/a/83194

here's results of running without and with `sudo -E` (with some cleaning up; sorted all env-vars, and removed build-specific random values)

[4_Nosudo.txt](https://github.com/moby/term/files/5470984/4_Nosudo.txt)
[6_Sudo -E.txt](https://github.com/moby/term/files/5470985/6_Sudo.-E.txt)

Without `sudo`, the `PATH` is

```
PATH=/home/runner/go/bin:/opt/hostedtoolcache/go/1.13.15/x64/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/opt/pipx_bin:/usr/share/rust/.cargo/bin:/home/runner/.config/composer/vendor/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

Whereas with `sudo -E`, path is the default:

```
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
```

**Comment by thaJeztah** [comment]
Success! It now properly fails with Go 1.13, but succeeds on Go 1.14 and Go 1.15 (as expected);

```
Error: ./term_test.go:21:4: t.Cleanup undefined (type *testing.T has no field or method Cleanup)
Error: ./term_test.go:35:4: t.Cleanup undefined (type *testing.T has no field or method Cleanup)
```

**Comment by thaJeztah** [comment]
Two years in the making; looks like it's ready for prime-time now 🎉 


@dims @cpuguy83 PTAL

**Review by dims — APPROVED** [review]
Sweet! nice clean ups in go.mod/sum

**Comment by thaJeztah** [comment]
Let me bring this one one 👍

**Pull request merged**
