### PR TITLE
Fix windows integer overflow

### PR DESCRIPTION
**Pull request by cpuguy83**
Makes it possible to build with GOOS=windows and GOARCH=arm

### CODE REVIEW

**Comment by thaJeztah** [comment]
related; https://github.com/moby/term/pull/14 ?

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by cpuguy83** [comment]
CI isn't testing on Windows, FYI.

**Comment by cpuguy83** [comment]
I'm definitely not an expert in these things.

These consts are defined as:

```go
	STD_INPUT_HANDLE  = -10 & (1<<32 - 1)
	STD_OUTPUT_HANDLE = -11 & (1<<32 - 1)
	STD_ERROR_HANDLE  = -12 & (1<<32 - 1)
```

**Comment by cpuguy83** [comment]
Yes, #14 seems related.

I need this for moby 20.10. It doesn't currently compile in our arm build pipeline.

**Review by tonistiigi — APPROVED** [review]

**Comment by thaJeztah** [comment]
Let's get this one in.

Perhaps we can get some traction on the upstream PRs https://github.com/Azure/go-ansiterm/pulls (have a WIP branch to make it use more of golang.org/x/sys/windows, which I think may help with some things)

**Pull request merged**
